[package]
name = "tengu-tensor-cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
tengu-tensor = { path = "../tengu-tensor" }
tengu-utils = { path = "../tengu-utils" }
anyhow = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
