[package]
name = "tengu-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tengu-backend-tensor = { path = "../tengu-backend-tensor" }
thiserror = { workspace = true }
anyhow = { workspace = true }
