[package]
name = "tengu-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tengu-tensor-traits = { path = "../tengu-tensor-traits" }
thiserror = { workspace = true }
anyhow = { workspace = true }
