[package]
name = "tengu-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tengu-tensor = { path = "../tengu-tensor" }
tengu-utils = { path = "../tengu-utils" }
thiserror = { workspace = true }
anyhow = { workspace = true }
