[package]
name = "tengu-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
thiserror = "1.0.63"
bon = "2.3.0"
bytemuck = "1.18.0"

[dev-dependencies]
winit = { version = "0.30.5", features = ["rwh_05"] }
