[package]
name = "tengu-tensor"
version = "0.1.0"
edition = "2021"

[dependencies]
tengu-utils = { path = "../tengu-utils" }
bytemuck = { workspace = true }
anyhow = { workspace = true }
itertools = "0.13.0"
